### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by haibianshifeng** [AhmedAlratrout/ContactAngle-Curvature-Roughness#2]
When I compile the code of ContacAngle on Ubuntu 14.04 using OpenFoam-v16.12+.

The errors appear, as following:

 surfaceRoughness
wmake	
make[1]: Entering directory `/home/lei/works/apps/contactAngle/surfaceRoughness'
g++ -std=c++11 -m64 -DOPENFOAM_PLUS=1612 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/surfMesh/lnInclude -IlnInclude -I. -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/OpenFOAM/lnInclude -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/OSspecific/POSIX/lnInclude   -fPIC -c surfaceRoughness.C -o Make/linux64GccDPInt32Opt/surfaceRoughness.o
surfaceRoughness.C: In function ‘int main(int, char**)’:
surfaceRoughness.C:107:38: error: ‘Foam::meshedSurface {aka class Foam::MeshedSurface<Foam::face>}’ has no member named ‘faces’
     const List<face> & faces=surf123.faces();
                                      ^
make[1]: *** [Make/linux64GccDPInt32Opt/surfaceRoughness.o] Error 1
make[1]: Leaving directory `/home/lei/works/apps/contactAngle/surfaceRoughness'
make: *** [wmake] Error 2
 surfaceAddLayerToCL
wmake	
make[1]: Entering directory `/home/lei/works/apps/contactAngle/surfaceAddLayerToCL'
g++ -std=c++11 -m64 -DOPENFOAM_PLUS=1612 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/surfMesh/lnInclude -IlnInclude -I. -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/OpenFOAM/lnInclude -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/OSspecific/POSIX/lnInclude   -fPIC -c surfaceAddLayerToCL.C -o Make/linux64GccDPInt32Opt/surfaceAddLayerToCL.o
surfaceAddLayerToCL.C: In function ‘int main(int, char**)’:
surfaceAddLayerToCL.C:72:37: error: ‘Foam::meshedSurface {aka class Foam::MeshedSurface<Foam::face>}’ has no member named ‘faces’
  const faceList &   faces = surf123.faces();
                                     ^
make[1]: *** [Make/linux64GccDPInt32Opt/surfaceAddLayerToCL.o] Error 1
make[1]: Leaving directory `/home/lei/works/apps/contactAngle/surfaceAddLayerToCL'
make: *** [wmake] Error 2
 surfaceSmoothVP
wmake	
make[1]: Entering directory `/home/lei/works/apps/contactAngle/surfaceSmoothVP'
g++ -std=c++11 -m64 -DOPENFOAM_PLUS=1612 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/surfMesh/lnInclude -IlnInclude -I. -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/OpenFOAM/lnInclude -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/OSspecific/POSIX/lnInclude   -fPIC -c surfaceSmoothVP.C -o Make/linux64GccDPInt32Opt/surfaceSmoothVP.o
surfaceSmoothVP.C: In function ‘int main(int, char**)’:
surfaceSmoothVP.C:120:38: error: ‘Foam::meshedSurface {aka class Foam::MeshedSurface<Foam::face>}’ has no member named ‘faces’
     const List<face> & faces=surf123.faces();
                                      ^
make[1]: *** [Make/linux64GccDPInt32Opt/surfaceSmoothVP.o] Error 1
make[1]: Leaving directory `/home/lei/works/apps/contactAngle/surfaceSmoothVP'
make: *** [wmake] Error 2
 voxelImage
g++ -std=c++0x -c  sphereToRaw.cpp
g++	-o	/home/lei/works/bin-v16/bin/sphereToRaw	sphereToRaw.o	
g++ -c -fPIC imageReader.cpp -o imageReader.o
g++ -c -fPIC voxelMesh.cpp -o voxelMesh.o
g++ -shared voxelMesh.o imageReader.o -o /home/lei/works/bin-v16/bin/libvoxelMesh.so
g++ -c imageFileConvert.cpp
g++	  -fPIC  -L/home/lei/works/bin-v16/bin/  imageFileConvert.o -lvoxelMesh -o	/home/lei/works/bin-v16/bin/imageFileConvert 
g++   -fPIC -c rawToFoam.cpp
g++	  -fPIC  -o	/home/lei/works/bin-v16/bin/rawToFoam -L/home/lei/works/bin-v16/bin rawToFoam.o -lvoxelMesh
rm  -f *.o
 voxelImageNew
g++ -O3 -Wall    poreGpCA.o  -o /home/lei/works/bin-v16/bin/poreGpCA 
ln -f -s /home/lei/works/bin-v16/bin/poreGpCA /home/lei/works/bin-v16/bin/imageFileConvert
g++ -O3 -Wall    writeRaCLInds.o  -o /home/lei/works/bin-v16/bin/writeRaCLInds 
ln -f -s /home/lei/works/bin-v16/bin/writeRaCLInds /home/lei/works/bin-v16/bin/imageFileConvert
g++ -O3 -Wall    writeRaPoreInds.o  -o /home/lei/works/bin-v16/bin/writeRaPoreInds 
ln -f -s /home/lei/works/bin-v16/bin/writeRaPoreInds /home/lei/works/bin-v16/bin/imageFileConvert
g++ -O3 -Wall    writepAreaPoreInds.o  -o /home/lei/works/bin-v16/bin/writepAreaPoreInds 
ln -f -s /home/lei/works/bin-v16/bin/writepAreaPoreInds /home/lei/works/bin-v16/bin/imageFileConvert
g++ -O3 -Wall    writeCAThroatInds.o  -o /home/lei/works/bin-v16/bin/writeCAThroatInds 
ln -f -s /home/lei/works/bin-v16/bin/writeCAThroatInds /home/lei/works/bin-v16/bin/imageFileConvert
g++ -O3 -Wall    writeRcThroatInds.o  -o /home/lei/works/bin-v16/bin/writeRcThroatInds 
ln -f -s /home/lei/works/bin-v16/bin/writeRcThroatInds /home/lei/works/bin-v16/bin/imageFileConvert
g++ -O3 -Wall    writeCAPoreInds.o  -o /home/lei/works/bin-v16/bin/writeCAPoreInds 
ln -f -s /home/lei/works/bin-v16/bin/writeCAPoreInds /home/lei/works/bin-v16/bin/imageFileConvert
g++ -O3 -Wall    writeRcPoreInds.o  -o /home/lei/works/bin-v16/bin/writeRcPoreInds 
ln -f -s /home/lei/works/bin-v16/bin/writeRcPoreInds /home/lei/works/bin-v16/bin/imageFileConvert
g++ -O3 -Wall    writeCACornerInds.o  -o /home/lei/works/bin-v16/bin/writeCACornerInds 
ln -f -s /home/lei/works/bin-v16/bin/writeCACornerInds /home/lei/works/bin-v16/bin/imageFileConvert
g++ -O3 -Wall    writeRcCornerInds.o  -o /home/lei/works/bin-v16/bin/writeRcCornerInds 
ln -f -s /home/lei/works/bin-v16/bin/writeRcCornerInds /home/lei/works/bin-v16/bin/imageFileConvert
g++ -O3 -Wall    Ufraw2Ucdat.o  -o /home/lei/works/bin-v16/bin/Ufraw2Ucdat 
g++	 -O3 -Wall  -std=c++0x  -o	/home/lei/works/bin-v16/bin/rawToFoamPar rawToFoamPar.o 
g++	   -std=c++0x  -o	/home/lei/works/bin-v16/bin/rawToFoam rawToFoam.o 
g++ -O3 -Wall    voxelImageConvert.o  -o /home/lei/works/bin-v16/bin/voxelImageConvert 
ln -f -s /home/lei/works/bin-v16/bin/voxelImageConvert /home/lei/works/bin-v16/bin/imageFileConvert
 voxelToSurfaceML
wmake
make[1]: Entering directory `/home/lei/works/apps/contactAngle/voxelToSurfaceML'
g++ -std=c++11 -m64 -DOPENFOAM_PLUS=1612 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -std=c++0x -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/finiteVolume/lnInclude -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/triSurface/lnInclude -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/surfMesh/lnInclude -I../voxelImage -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/meshTools/lnInclude -IlnInclude -I. -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/OpenFOAM/lnInclude -I/home/lei/OpenFOAM/OpenFOAM-v1612+/src/OSspecific/POSIX/lnInclude   -fPIC -c voxelToSurface.C -o Make/linux64GccDPInt32Opt/voxelToSurface.o
In file included from voxelToSurface.C:31:0:
../voxelImage/voxelMesh.h: In member function ‘bool voxelField<Type>::readBin(std::string, int, int, int, int, int, int)’:
../voxelImage/voxelMesh.h:242:55: warning: use of old-style cast [-Wold-style-cast]
                 in.read((char*)(&(*this)[k][j][iStart]),
                                                       ^
../voxelImage/voxelMesh.h: In member function ‘void voxelField<Type>::writeBin(std::string, int, int, int, int, int, int) const’:
../voxelImage/voxelMesh.h:285:58: warning: use of old-style cast [-Wold-style-cast]
                 of.write((char*)(&((*this)[k][j][iStart])),
                                                          ^
../voxelImage/voxelMesh.h: In member function ‘void voxelField<Type>::writeRotatedXZ(std::ofstream&) const’:
../voxelImage/voxelMesh.h:329:44: warning: use of old-style cast [-Wold-style-cast]
                 of<<(double)(*this)[k][j][i]<<' ';
                                            ^
In file included from voxelToSurface.C:49:0:
createSurface.h: In function ‘int appendSinglyConnectedNeis(Foam::label, Foam::DynamicList<int>&, const meshedSurface&, Foam::labelList&, bool)’:
createSurface.h:585:34: error: ‘const meshedSurface {aka const class Foam::MeshedSurface<Foam::face>}’ has no member named ‘faces’
  const List<face>& faces = surf1.faces();
                                  ^
createSurface.h: In function ‘void correct(Foam::faceList&, Foam::labelList&, Foam::DynamicField<Foam::Vector<double> >&, bool)’:
createSurface.h:687:35: error: ‘class Foam::MeshedSurface<Foam::face>’ has no member named ‘faces’
  const List<face>& Sfaces = surf1.faces();
                                   ^
make[1]: *** [Make/linux64GccDPInt32Opt/voxelToSurface.o] Error 1
make[1]: Leaving directory `/home/lei/works/apps/contactAngle/voxelToSurfaceML'
make: *** [wmake] Error 2

**Comment by AhmedAlratrout** [comment]
Thanks. I appreciate your kind interest in the code.

I think this is a compatibility issue with the openFOAM-v1612+ version. Please replace this version with an older openFOAM-v1606+ version https://www.openfoam.com/releases/openfoam-v1606+/. Please let me know how it goes.
